#import './treeFields.fragment.gql'

query AreasTree($filter: AreaFilterInput!) {
  areasTree(filter: $filter) {
    ...TreeFields
    children {
    ...TreeFields
      children {
        ...TreeFields
        children {
          ...TreeFields
        }
      }
    }
  }
}